### ISSUE TITLE
Acorn will delete a volume that already exists when the app is removed

### ISSUE THREAD

**Issue by cloudnautique** [acorn-io/acorn#492] opened 2022-08-08 19:19 UTC
If you bind a pre-existing volume into an Acorn then remove that app, the volume is deleted. 

On Rancher desktop create a 1G volume in the dashboard using hostpath, and assign to local-path storage class. 

```
 containers: {                                                                                 
     web: {
         image: "nginx"
         ports: "8080:80/tcp"
         files: {
           "/tmp/secretconfig.txt": "secret://testing/template"
         }
         dirs: {
             "/data": "volume://webd"
         }
     }
     cache: image: "redis"
} 
volumes: {
   webd:{}
}
```

then run:

`acorn run -v my-existing-volume:webd,size=1G,class=local-path $(acorn build .)`

When you remove that app, it deletes the my-existing-volume.

**Comment by ibuildthecloud** [comment] 2022-08-08 19:23
@cloudnautique What is the persistentVolumeReclaimPolicy of the existing PV?  We need that to be "Retain", maybe we don't update it, I thought we did.

**Comment by cjellick** [comment] 2022-08-09 16:17
Putting in v0.2.0 because if this is legit, we'll want to address it soon

**Comment by thedadams** [comment] 2022-08-18 02:06
For whatever it's worth: I am not able to reproduce this using Rancher Desktop v1.5.1, Kubernetes v1.23.8, and Acorn v0.1.2. The volume I created had its `PersistentVolumeReclaimPolicy` set to `Retain` by default.

**Comment by cjellick** [comment] 2022-10-05 17:18
I am going to put this in v0.4.0 and send to "QA" for reverification.

**Comment by cjellick** [comment] 2022-10-05 17:19
@cloudnautique can you retest sometime next week?

**Comment by jsilverio22** [comment] 2022-11-17 17:40
QA: 
Acornfile: 
` containers: {                                                                                 
     web: {
         image: "nginx"
         ports: "80/http"
         dirs: {
             "/data": "volume://webd"
         }
     }
     cache: image: "redis"
} 
volumes: {
   webd:{}
}
`

`jsilverio@joshuas-mbp acorn % ./bin/acorn run                                                    
[+] Building 0.5s (5/5) FINISHED                                                                                                                                                     
 => [internal] load .dockerignore                                                                                                                                               0.1s
 => => transferring context: 84B                                                                                                                                                0.0s
 => [internal] load build definition from acorn-dockerfile-1084471615                                                                                                           0.1s
 => => transferring dockerfile: 65B                                                                                                                                             0.0s
 => [internal] load metadata for docker.io/library/redis:latest                                                                                                                 0.4s
 => CACHED [1/1] FROM docker.io/library/redis@sha256:1e3207c292225b6dd21cb74d59255748a50e8f739dd983040df38fa913927cf1                                                           0.0s
 => => resolve docker.io/library/redis@sha256:1e3207c292225b6dd21cb74d59255748a50e8f739dd983040df38fa913927cf1                                                                  0.0s
 => exporting to image                                                                                                                                                          0.0s
 => => exporting layers                                                                                                                                                         0.0s
 => => exporting manifest sha256:6ec4d5b6c6a527a1146a7439c46afe444ac9779c6ee52e63ba2a569953a9bf5c                                                                               0.0s
 => => exporting config sha256:f42da784aae2c6b0857e82d2c711514591cfa9cf9ec54e9ac3f98311ce29a0cd                                                                                 0.0s
 => => pushing layers                                                                                                                                                           0.0s
 => => pushing manifest for 127.0.0.1:5000/acorn/acorn:latest@sha256:6ec4d5b6c6a527a1146a7439c46afe444ac9779c6ee52e63ba2a569953a9bf5c                                           0.0s
[+] Building 0.3s (5/5) FINISHED                                                                                                                                                     
 => [internal] load build definition from acorn-dockerfile-642519215                                                                                                            0.1s
 => => transferring dockerfile: 64B                                                                                                                                             0.1s
 => [internal] load .dockerignore                                                                                                                                               0.1s
 => => transferring context: 84B                                                                                                                                                0.1s
 => [internal] load metadata for docker.io/library/nginx:latest                                                                                                                 0.2s
 => CACHED [1/1] FROM docker.io/library/nginx@sha256:e209ac2f37c70c1e0e9873a5f7231e91dcd83fdf1178d8ed36c2ec09974210ba                                                           0.0s
 => => resolve docker.io/library/nginx@sha256:e209ac2f37c70c1e0e9873a5f7231e91dcd83fdf1178d8ed36c2ec09974210ba                                                                  0.0s
 => exporting to image                                                                                                                                                          0.0s
 => => exporting layers                                                                                                                                                         0.0s
 => => exporting manifest sha256:408443732e9f7b5ed5f7fbcc07fd5da08ed6f2df7f56088bb763aa0da00cb2c8                                                                               0.0s
 => => exporting config sha256:4d5523011a65a0d235df7ff1932bdb244789d1f2166a3337d6e86205e50711c8                                                                                 0.0s
 => => pushing layers                                                                                                                                                           0.0s
 => => pushing manifest for 127.0.0.1:5000/acorn/acorn:latest@sha256:408443732e9f7b5ed5f7fbcc07fd5da08ed6f2df7f56088bb763aa0da00cb2c8                                           0.0s
[+] Building 0.0s (5/5) FINISHED                                                                                                                                                     
 => [internal] load build definition from Dockerfile                                                                                                                            0.0s
 => => transferring dockerfile: 58B                                                                                                                                             0.0s
 => [internal] load .dockerignore                                                                                                                                               0.0s
 => => transferring context: 64B                                                                                                                                                0.0s
 => [internal] load build context                                                                                                                                               0.0s
 => => transferring context: 671B                                                                                                                                               0.0s
 => CACHED [1/1] COPY . /                                                                                                                                                       0.0s
 => exporting to image                                                                                                                                                          0.0s
 => => exporting layers                                                                                                                                                         0.0s
 => => exporting manifest sha256:b7512f07f71654de3aae46b63b116937fc050656ba94fae1e1abcb561308ce64                                                                               0.0s
 => => exporting config sha256:f05376c66b990c75b3168c4cb2004a58fc5faa71e3db0a3503524b093a9f46cb                                                                                 0.0s
 => => pushing layers                                                                                                                                                           0.0s
 => => pushing manifest for 127.0.0.1:5000/acorn/acorn:latest@sha256:b7512f07f71654de3aae46b63b116937fc050656ba94fae1e1abcb561308ce64                                           0.0s
snowy-water
STATUS: ENDPOINTS[] HEALTHY[] UPTODATE[] 
STATUS: ENDPOINTS[] HEALTHY[0] UPTODATE[0] pending
STATUS: ENDPOINTS[] HEALTHY[0/2] UPTODATE[2] [containers: cache ContainerCreating; web is not scheduled to a node]
STATUS: ENDPOINTS[] HEALTHY[1/2] UPTODATE[2] [containers: web is not scheduled to a node]
STATUS: ENDPOINTS[] HEALTHY[1/2] UPTODATE[2] [containers: web ContainerCreating]
┌───────────────────────────────────────────────┐
| STATUS: ENDPOINTS[] HEALTHY[2] UPTODATE[2] OK |
└───────────────────────────────────────────────┘

┌───────────────────────────────────────────────┐
| STATUS: ENDPOINTS[] HEALTHY[2] UPTODATE[2] OK |
└───────────────────────────────────────────────┘
jsilverio@joshuas-mbp acorn % ./bin/acorn all

APPS:
NAME          IMAGE          HEALTHY   UP-TO-DATE   CREATED   ENDPOINTS   MESSAGE
snowy-water   afa4d9492470   2         2            5s ago                OK

CONTAINERS:
NAME                                 APP           IMAGE     STATE     RESTARTCOUNT   CREATED   MESSAGE
snowy-water.cache-657bd78745-tq52n   snowy-water   redis     running   0              5s ago    
snowy-water.web-6f5cc69c78-xzg8b     snowy-water   nginx     running   0              5s ago    

VOLUMES:
NAME                                       APP-NAME      BOUND-VOLUME   CAPACITY   STATUS    ACCESS-MODES   CREATED
pvc-40c7083c-84f1-4c58-ba70-22841efc956f   snowy-water   webd           10G        bound     RWO            5s ago

SECRETS:
ALIAS     NAME      TYPE      KEYS      CREATED
jsilverio@joshuas-mbp acorn % ./bin/acorn rm snowy-water
snowy-water
? Do you want to remove the above app Yes
Removed: snowy-water
snowy-water.cache-657bd78745-tq52n
snowy-water.web-6f5cc69c78-xzg8b
? Do you want to remove the above containers Yes
Removed: snowy-water.cache-657bd78745-tq52n
Removed: snowy-water.web-6f5cc69c78-xzg8b
jsilverio@joshuas-mbp acorn % ./bin/acorn all           

APPS:
NAME      IMAGE     HEALTHY   UP-TO-DATE   CREATED   ENDPOINTS   MESSAGE

CONTAINERS:
NAME      APP       IMAGE     STATE     RESTARTCOUNT   CREATED   MESSAGE

VOLUMES:
NAME                                       APP-NAME      BOUND-VOLUME   CAPACITY   STATUS     ACCESS-MODES   CREATED
pvc-40c7083c-84f1-4c58-ba70-22841efc956f   snowy-water   webd           10G        released   RWO            71s ago

SECRETS:
ALIAS     NAME      TYPE      KEYS      CREATED
jsilverio@joshuas-mbp acorn % 
`

**Closed by jsilverio22** 2022-11-17 17:40 UTC
Labels: bug
