### ISSUE TITLE
Not able to use local images as service images.

### ISSUE THREAD

**Issue by sangee2004** [acorn-io/acorn#1607] opened 2023-05-16 01:01 UTC
acorn version v0.7.0-alpha1-45-g5253ebae+5253ebae

Steps to reproduce the problem:
Build a service Acorn image locally using `acorn build -t myfirstservice:v0.0.1 -f Acornfilecon .`
Try to use this image as service image when deploying apps:
```
containers: {
  nginx: {
    image: "nginx"
    env: {
     "SECRET": "@{secrets.mysec.output.key}"
     "ADDRESS": "@{services.mysec.address}"
     "PORT": "@{services.mysec.ports.3306}"
     "value1": "@{services.mysec.data.test1}"
     "value2": "@{services.mysec.data.test2}"
}
}
}
services: {
     mysec: {
	image: "myfirstservice:v0.0.1"
        }
}
```

App deployment fails with following error:
```  ✗  ERROR:  missing registry host in the tag [myfirstservice:v0.0.1] (ie ghcr.io or docker.io)```

**Comment by cjellick** [comment] 2023-06-05 15:46
closing as a dupe of #1605

**Comment by cjellick** [comment] 2023-06-05 15:50
bumping out. this will need release noted

**Comment by g-linville** [comment] 2023-06-12 18:51
I tested this locally and it looks like it was fixed by the same PR that I made to fix it for nested Acorns.

**Closed** 2023-06-12 19:01 UTC
Labels: kind/bug, area/service
