### ISSUE TITLE
Auto upgrade not working with * & ** special characters

### ISSUE THREAD

**Issue by samkulkarni20** [acorn-io/acorn#1032] opened 2023-01-13 16:20 UTC
I have a package published with tag `v2.2-alpha` & tried to run it with below auto upgrade enabled commands, but it didn't work.
As you can see below, only the rules that contain `*` or `**` don't work. I do have the application image published with specific tag.
```
$ acorn run -n nginx-golang ghcr.io/samkulkarni20/nginx-golang:v#.#-* 
zsh: no matches found: ghcr.io/samkulkarni20/nginx-golang:v#.#-*
$ acorn run -n nginx-golang ghcr.io/samkulkarni20/nginx-golang:v#.#-**
zsh: no matches found: ghcr.io/samkulkarni20/nginx-golang:v#.#-**
$ acorn run -n nginx-golang ghcr.io/samkulkarni20/nginx-golang:v2.2-* 
zsh: no matches found: ghcr.io/samkulkarni20/nginx-golang:v2.2-*
```
My Acorn version:
```
$ acorn -v                                                           
acorn version v0.4.2+e23f68d4
```
Auto upgrade command with just `#` works fine
```
$acorn run -n nginx-golang ghcr.io/samkulkarni20/nginx-golang:v#.#   
nginx-golang

$ acorn apps                                                       
NAME           IMAGE                                     HEALTHY   UP-TO-DATE   CREATED   ENDPOINTS                                                              MESSAGE
nginx-golang   ghcr.io/samkulkarni20/nginx-golang:v2.1   2         2            13s ago   http://proxy-nginx-golang-1fe838eb7a71.local.on-acorn.io/ => proxy:80   OK
```
Images in my container registry:
![Screenshot from 2023-01-13 13-46-51](https://user-images.githubusercontent.com/15933023/212368142-a7c60b15-97d2-4862-b007-45e8fc98eff0.png)

**Comment by thedadams** [comment] 2023-01-13 18:23
Hi @samkulkarni20! Thank you for bringing this up.

As you can see from the message you have posted above, the error `no matches found` is actually coming from you shell `zsh`. This is because `zsh` sees the wildcard and tries to expand it. This is not what you want.

I think trying something like `acorn run -n nginx-golang "ghcr.io/samkulkarni20/nginx-golang:v#.#-*"` will work for you. Please let us know if you still have trouble.

**Comment by cjellick** [comment] 2023-01-13 20:24
closing. Feel free to reopen if this doesnt address your issue @samkulkarni20

**Comment by cjellick** [comment] 2023-01-17 16:11
Reopened. @samkulkarni20 reported more funky behavior in user slack: https://acorn-users.slack.com/archives/C03R9ME0SKC/p1673597849244369?thread_ts=1673421741.777379&cid=C03R9ME0SKC

**Comment by sangee2004** [comment] 2023-02-03 21:53
Able to reproduce this issue with `v0.5.1+46fe4aef`

acorn run -n mytestapp "mytest:v#.#-*"

App deploys successfully.

acorn rm mytestapp 

Remove app and redploy the app. App is stuck in "waiting for image to satisfy auto-upgrade " forever.

acorn run -n mytestapp "mytest:v#.#-*"
```
mytestapp
STATUS: ENDPOINTS[] HEALTHY[] UPTODATE[] 
STATUS: ENDPOINTS[] HEALTHY[0] UPTODATE[0] [image-pull: waiting for image to satisfy auto-upgrade tag v#.#-*]
^C  ✗  ERROR:  terminating watch: context canceled

```
This issue is fixed when testing with latest builds from master -  `acorn version v0.5.1-28-g099c492+099c492f`


% acorn run -n mytestapp "mytest:v#.#-*"

App deploys successfully.

% acorn rm mytestapp 
Removed: mytestapp
% acorn run -n mytestapp "mytest:v#.#-*"
```
mytestapp
STATUS: ENDPOINTS[] HEALTHY[] UPTODATE[] 
STATUS: ENDPOINTS[] HEALTHY[0] UPTODATE[0] pending
STATUS: ENDPOINTS[] HEALTHY[0/1] UPTODATE[1] [containers: nginx1 ContainerCreating]
```

**Comment by sangee2004** [comment] 2023-02-06 19:14
@samkulkarni20 This issue is fixed on latest main builds - https://docs.acorn.io/installation/installing#development-binaries-main-build and will be made available in future release. Please feel free to reopen this issue if you still encounter this issue with builds having the fix.

**Closed by sangee2004** 2023-02-06 19:14 UTC
Labels: bug
